const authForm = document.getElementById('merchantAuthForm');
const queryForm = document.getElementById('merchantQueryForm');
const toast = document.getElementById('toast');
const rememberInput = authForm.elements.rememberPassword;
const rememberKey = 'campus_merchant_login';
let registerMode = false;
function show(message, error = false) { toast.textContent = message; toast.classList.toggle('error', error); toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3200); }
async function call(path, options = {}) { const response = await fetch(path, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || '请求失败'); return data; }
function renderAuth(mode) { registerMode = mode; document.getElementById('merchantTitle').textContent = mode ? '注册商家账号' : '登录商家账号'; document.getElementById('merchantNameLabel').hidden = !mode; document.getElementById('merchantConfirmLabel').hidden = !mode; document.getElementById('merchantAuthSubmit').textContent = mode ? '注册并进入' : '登录'; document.querySelector('#merchantSwitch button').textContent = mode ? '返回登录' : '注册'; }
function openWorkspace() { authForm.hidden = true; document.getElementById('merchantSwitch').hidden = true; document.getElementById('merchantWorkspace').hidden = false; document.getElementById('merchantTitle').textContent = '商家兑换查询'; }
try {
  const saved = JSON.parse(localStorage.getItem(rememberKey) || 'null');
  if (saved?.phone) { authForm.elements.phone.value = saved.phone; authForm.elements.password.value = saved.password || ''; rememberInput.checked = true; }
} catch { /* Ignore unavailable or invalid browser storage. */ }
authForm.addEventListener('submit', async (event) => { event.preventDefault(); try { await call(`/api/merchant/${registerMode ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(authForm).entries())) }); if (rememberInput.checked) localStorage.setItem(rememberKey, JSON.stringify({ phone: authForm.elements.phone.value.trim(), password: authForm.elements.password.value })); else localStorage.removeItem(rememberKey); openWorkspace(); } catch (error) { show(error.message, true); } });
document.querySelector('#merchantSwitch button').addEventListener('click', () => renderAuth(!registerMode));
queryForm.addEventListener('submit', async (event) => { event.preventDefault(); try { const result = await call('/api/merchant/query', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(queryForm).entries())) }); const record = result.record; document.getElementById('merchantResult').innerHTML = `<article class="record-item"><strong>${result.status === 'verified' ? '已核验' : '未核验'}</strong><small>${result.message}</small>${record ? `<small>${record.name} · ${record.schoolName} · ${record.college}</small>` : ''}${result.canConfirm ? '<button class="primary-button" id="merchantActivate" type="button">确认激活</button>' : ''}</article>`; document.getElementById('merchantActivate')?.addEventListener('click', async () => { try { const confirmed = await call('/api/merchant/confirm-activation', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ campusNumber: queryForm.elements.campusNumber.value.trim() }) }); show(confirmed.message); queryForm.requestSubmit(); } catch (error) { show(error.message, true); } }); } catch (error) { show(error.message, true); } });
document.getElementById('merchantLogout').addEventListener('click', async () => { await fetch('/api/merchant/logout', { method: 'POST' }); location.reload(); });
fetch('/api/merchant/session').then((response) => response.json()).then((session) => { if (session.authenticated) openWorkspace(); else if (!session.registrationEnabled) document.getElementById('merchantSwitch').hidden = true; });
