const { request } = require('../../utils/api');
const app = getApp();
Page({
  data: { title: '', kind: 'order', isNumberOrder: false, name: '', studentNo: '', phone: '', code: '', address: '', detail: '', appointment: '尽快联系', appointments: ['尽快联系', '上午 09:00 - 12:00', '下午 14:00 - 18:00', '晚上 18:00 - 20:30'], numbers: [], selectedNumber: '正在加载可选号码...', selectedOfferId: '', methods: ['快递配送', '上门激活', '迎新点办理'], fulfillmentMethod: '快递配送', serviceConsent: false, marketingConsent: false, countdown: 0 },
  onLoad(query) { const title = decodeURIComponent(query.title || '校园网账号预约'); const isNumberOrder = title.includes('选号'); this.setData({ title, kind: query.kind || 'order', isNumberOrder }); wx.setNavigationBarTitle({ title }); if (isNumberOrder) this.loadOffers(); },
  async loadOffers() { try { const result = await request(`/api/schools/${encodeURIComponent(app.globalData.schoolCode)}/numbers`); this.offerList = result.offers; this.setData({ numbers: result.offers.map((offer) => `${offer.displayNumber} · ${offer.planName} · ${offer.monthlyFee} 元/月`), selectedNumber: result.offers.length ? '请选择意向号码' : '当前没有可选号码' }); } catch (error) { this.setData({ selectedNumber: '号码加载失败' }); wx.showToast({ title: error.message, icon: 'none' }); } },
  setField(event) { this.setData({ [event.currentTarget.dataset.key]: event.detail.value }); },
  pickNumber(event) { const index = Number(event.detail.value); const offer = this.offerList?.[index]; if (offer) this.setData({ selectedNumber: this.data.numbers[index], selectedOfferId: offer.id }); },
  pickMethod(event) { this.setData({ fulfillmentMethod: this.data.methods[event.detail.value] }); },
  pickAppointment(event) { this.setData({ appointment: this.data.appointments[event.detail.value] }); },
  toggleService(event) { this.setData({ serviceConsent: event.detail.value.length > 0 }); },
  toggleMarketing(event) { this.setData({ marketingConsent: event.detail.value.length > 0 }); },
  async sendCode() { try { const result = await request('/api/student/code', 'POST', { schoolCode: app.globalData.schoolCode, phone: this.data.phone, purpose: 'submit' }); if (result.developmentCode) wx.showToast({ title: `开发验证码：${result.developmentCode}`, icon: 'none', duration: 4000 }); else wx.showToast({ title: '验证码已发送', icon: 'success' }); this.countDown(); } catch (error) { wx.showToast({ title: error.message, icon: 'none' }); } },
  countDown() { let seconds = 60; this.setData({ countdown: seconds }); const timer = setInterval(() => { seconds -= 1; this.setData({ countdown: seconds }); if (!seconds) clearInterval(timer); }, 1000); },
  async submit() { const d = this.data; if (!d.serviceConsent) return wx.showToast({ title: '请先同意必要信息处理说明', icon: 'none' }); if (d.isNumberOrder && !d.selectedOfferId) return wx.showToast({ title: '请选择意向号码', icon: 'none' }); const payload = { schoolCode: app.globalData.schoolCode, type: d.title, name: d.name, studentNo: d.studentNo, phone: d.phone, code: d.code, address: d.address, appointment: d.appointment, detail: d.detail, serviceConsent: d.serviceConsent, marketingConsent: d.marketingConsent, selectedOfferId: d.isNumberOrder ? d.selectedOfferId : '', fulfillmentMethod: d.isNumberOrder ? d.fulfillmentMethod : '' }; try { const result = await request(d.kind === 'ticket' ? '/api/tickets' : '/api/orders', 'POST', payload); wx.showModal({ title: '提交成功', content: `服务编号：${result.record.id}`, showCancel: false, success: () => wx.navigateBack() }); } catch (error) { wx.showToast({ title: error.message, icon: 'none' }); } }
});
