const { request } = require('../../utils/api');
const app = getApp();
Page({
  data: { title: '', kind: 'order', isNumberOrder: false, name: '', studentNo: '', idCard: '', college: '', phone: '', shippingRecipient: '', shippingPhone: '', shippingAddress: '', appointment: '尽快联系', appointments: ['尽快联系', '上午 09:00 - 12:00', '下午 14:00 - 18:00', '晚上 18:00 - 20:30'], operators: ['中国移动', '中国联通', '中国电信'], operator: '中国移动', numbers: [], selectedNumber: '正在加载可选号码...', selectedOfferId: '', page: 1, totalPages: 1, methods: [], fulfillmentMethod: '', serviceConsent: false, marketingConsent: false },
  onLoad(query) { const title = decodeURIComponent(query.title || '校园网账号预约'); const isNumberOrder = title.includes('选号'); this.setData({ title, kind: query.kind || 'order', isNumberOrder }); wx.setNavigationBarTitle({ title }); if (isNumberOrder) this.loadOffers(); },
  async loadOffers() { try { const result = await request(`/api/schools/${encodeURIComponent(app.globalData.schoolCode)}/numbers?operator=${encodeURIComponent(this.data.operator)}&page=${this.data.page}&pageSize=30`); this.offerList = result.offers; this.setData({ numbers: result.offers.map((offer) => `${offer.displayNumber} · ${offer.planName} · ${offer.monthlyFee} 元/月`), selectedNumber: result.offers.length ? '请选择意向号码' : '当前没有可选号码', totalPages: result.totalPages || 1 }); } catch (error) { this.setData({ selectedNumber: '号码加载失败' }); wx.showToast({ title: error.message, icon: 'none' }); } },
  setField(event) { this.setData({ [event.currentTarget.dataset.key]: event.detail.value }); },
  pickOperator(event) { this.setData({ operator: this.data.operators[event.detail.value], page: 1, selectedOfferId: '' }, () => this.loadOffers()); },
  pickNumber(event) { const index = Number(event.detail.value); const offer = this.offerList?.[index]; if (offer) this.setData({ selectedNumber: this.data.numbers[index], selectedOfferId: offer.id }); },
  previousPage() { if (this.data.page > 1) this.setData({ page: this.data.page - 1, selectedOfferId: '' }, () => this.loadOffers()); },
  nextPage() { if (this.data.page < this.data.totalPages) this.setData({ page: this.data.page + 1, selectedOfferId: '' }, () => this.loadOffers()); },
  pickAppointment(event) { this.setData({ appointment: this.data.appointments[event.detail.value] }); },
  toggleService(event) { this.setData({ serviceConsent: event.detail.value.length > 0 }); },
  toggleMarketing(event) { this.setData({ marketingConsent: event.detail.value.length > 0 }); },
  async submit() { const d = this.data; if (!d.name || !d.idCard || !d.college || !d.phone || !d.shippingRecipient || !d.shippingPhone || !d.shippingAddress) return wx.showToast({ title: '请完整填写身份信息和收货信息', icon: 'none' }); if (!/^1\d{10}$/.test(d.shippingPhone)) return wx.showToast({ title: '联系号码格式不正确', icon: 'none' }); if (!d.serviceConsent) return wx.showToast({ title: '请先同意信息收集和后续联系说明', icon: 'none' }); if (d.isNumberOrder && !d.selectedOfferId) return wx.showToast({ title: '请选择意向号码', icon: 'none' }); const payload = { schoolCode: app.globalData.schoolCode, type: d.title, name: d.name, studentNo: d.studentNo, idCard: d.idCard, college: d.college, phone: d.phone, shippingRecipient: d.shippingRecipient, shippingPhone: d.shippingPhone, shippingAddress: d.shippingAddress, appointment: d.appointment, serviceConsent: d.serviceConsent, marketingConsent: d.marketingConsent, selectedOfferId: d.isNumberOrder ? d.selectedOfferId : '' }; try { const result = await request('/api/orders', 'POST', payload); wx.showModal({ title: '提交成功', content: `服务编号：${result.record.id}`, showCancel: false, success: () => wx.navigateBack() }); } catch (error) { wx.showToast({ title: error.message, icon: 'none' }); } }
});
