CREATE DATABASE IF NOT EXISTS CampusService CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE CampusService;
CREATE TABLE IF NOT EXISTS campus_snapshot (
  id TINYINT PRIMARY KEY,
  payload JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
